setwd("~/Dropbox/DATA ANALYSIS/R Exercises/Exploratory Data Analysis/Project 1")
DataSet<-read.table(pipe('grep "^[1-2]/2/2007" "household_power_consumption.txt"'),header=FALSE,sep=';')
colnames(DataSet)<-names(read.table('household_power_consumption.txt',header=TRUE,sep=';',nrows=1))
# Previous 2 lines of code suggested by eyal soreq in discussion forum
DataSet$DateTime<-strptime(paste(DataSet$Date,DataSet$Time), format="%d/%m/%Y %H:%M:%S")
# Creates new variable combining Date and Time
par(mfrow=c(2,2))
with(DataSet,plot(DateTime,Global_active_power,type="l",ylab="Global Active Power",xlab=""))
with(DataSet,plot(DateTime,Voltage,type="l",ylab="Voltage"))
with(DataSet,plot(DateTime,Sub_metering_1,type="l",ylab="Energy sub metering",xlab=""))
with(DataSet,lines(DateTime,Sub_metering_2,type="l",col="red"))
with(DataSet,lines(DateTime,Sub_metering_3,type="l",col="blue"))
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"),cex=.75)
with(DataSet,plot(DateTime,Global_reactive_power,type="l",ylab="Global Reactive Power"))
dev.copy(png,'plot4.png')
dev.off()